// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyFilter(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['Service']['ApplyFilter'](arg1, arg2, arg3, arg4, arg5);
}

export function ApplyLevelsSample(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['Service']['ApplyLevelsSample'](arg1, arg2, arg3, arg4);
}

export function BeginExportPreview() {
  return window['go']['bridge']['Service']['BeginExportPreview']();
}

export function BeginFilterEdit(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['Service']['BeginFilterEdit'](arg1, arg2, arg3, arg4, arg5);
}

export function BeginHealStroke(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['bridge']['Service']['BeginHealStroke'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function BeginImageImport(arg1) {
  return window['go']['bridge']['Service']['BeginImageImport'](arg1);
}

export function BeginStroke(arg1, arg2) {
  return window['go']['bridge']['Service']['BeginStroke'](arg1, arg2);
}

export function CameraRawAutoWhiteBalance() {
  return window['go']['bridge']['Service']['CameraRawAutoWhiteBalance']();
}

export function CameraRawDefringeSample(arg1, arg2, arg3) {
  return window['go']['bridge']['Service']['CameraRawDefringeSample'](arg1, arg2, arg3);
}

export function CameraRawScope() {
  return window['go']['bridge']['Service']['CameraRawScope']();
}

export function CameraRawWhiteBalanceSample(arg1, arg2) {
  return window['go']['bridge']['Service']['CameraRawWhiteBalanceSample'](arg1, arg2);
}

export function CancelFilterEdit() {
  return window['go']['bridge']['Service']['CancelFilterEdit']();
}

export function CancelImageImport() {
  return window['go']['bridge']['Service']['CancelImageImport']();
}

export function CancelPendingOpen() {
  return window['go']['bridge']['Service']['CancelPendingOpen']();
}

export function CommitFilter(arg1) {
  return window['go']['bridge']['Service']['CommitFilter'](arg1);
}

export function ConfirmPendingOpen() {
  return window['go']['bridge']['Service']['ConfirmPendingOpen']();
}

export function CopyMerged() {
  return window['go']['bridge']['Service']['CopyMerged']();
}

export function DocumentSnapshot() {
  return window['go']['bridge']['Service']['DocumentSnapshot']();
}

export function EndExportPreview() {
  return window['go']['bridge']['Service']['EndExportPreview']();
}

export function EndHealStroke() {
  return window['go']['bridge']['Service']['EndHealStroke']();
}

export function EndStroke() {
  return window['go']['bridge']['Service']['EndStroke']();
}

export function ExportJPEG(arg1, arg2, arg3) {
  return window['go']['bridge']['Service']['ExportJPEG'](arg1, arg2, arg3);
}

export function ExportJPEGPreview(arg1, arg2) {
  return window['go']['bridge']['Service']['ExportJPEGPreview'](arg1, arg2);
}

export function ExportPNG(arg1) {
  return window['go']['bridge']['Service']['ExportPNG'](arg1);
}

export function FinishImageImport() {
  return window['go']['bridge']['Service']['FinishImageImport']();
}

export function HealPoint(arg1, arg2) {
  return window['go']['bridge']['Service']['HealPoint'](arg1, arg2);
}

export function LayerHistogram() {
  return window['go']['bridge']['Service']['LayerHistogram']();
}

export function LayerOp(arg1, arg2) {
  return window['go']['bridge']['Service']['LayerOp'](arg1, arg2);
}

export function LevelsAuto(arg1) {
  return window['go']['bridge']['Service']['LevelsAuto'](arg1);
}

export function OpenProjectDialog() {
  return window['go']['bridge']['Service']['OpenProjectDialog']();
}

export function PickImageImport() {
  return window['go']['bridge']['Service']['PickImageImport']();
}

export function RawBeginDevelop(arg1) {
  return window['go']['bridge']['Service']['RawBeginDevelop'](arg1);
}

export function RawCancelDevelop() {
  return window['go']['bridge']['Service']['RawCancelDevelop']();
}

export function RawDevelopPreview(arg1) {
  return window['go']['bridge']['Service']['RawDevelopPreview'](arg1);
}

export function RawFinishDevelop(arg1, arg2) {
  return window['go']['bridge']['Service']['RawFinishDevelop'](arg1, arg2);
}

export function Redo() {
  return window['go']['bridge']['Service']['Redo']();
}

export function RenderHandler() {
  return window['go']['bridge']['Service']['RenderHandler']();
}

export function SampleLevelsPoint(arg1, arg2) {
  return window['go']['bridge']['Service']['SampleLevelsPoint'](arg1, arg2);
}

export function SaveProjectDialog() {
  return window['go']['bridge']['Service']['SaveProjectDialog']();
}

export function SelectObjectAt(arg1, arg2) {
  return window['go']['bridge']['Service']['SelectObjectAt'](arg1, arg2);
}

export function SelectSubject() {
  return window['go']['bridge']['Service']['SelectSubject']();
}

export function Startup(arg1) {
  return window['go']['bridge']['Service']['Startup'](arg1);
}

export function StrokePoint(arg1, arg2) {
  return window['go']['bridge']['Service']['StrokePoint'](arg1, arg2);
}

export function Undo() {
  return window['go']['bridge']['Service']['Undo']();
}

export function UpdateFilterPreview(arg1) {
  return window['go']['bridge']['Service']['UpdateFilterPreview'](arg1);
}

export function Version() {
  return window['go']['bridge']['Service']['Version']();
}
