// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginStroke(arg1, arg2) {
  return window['go']['bridge']['Service']['BeginStroke'](arg1, arg2);
}

export function DocumentSnapshot() {
  return window['go']['bridge']['Service']['DocumentSnapshot']();
}

export function EndStroke() {
  return window['go']['bridge']['Service']['EndStroke']();
}

export function LayerOp(arg1, arg2) {
  return window['go']['bridge']['Service']['LayerOp'](arg1, arg2);
}

export function OpenProjectDialog() {
  return window['go']['bridge']['Service']['OpenProjectDialog']();
}

export function Redo() {
  return window['go']['bridge']['Service']['Redo']();
}

export function RenderHandler() {
  return window['go']['bridge']['Service']['RenderHandler']();
}

export function SaveProjectDialog() {
  return window['go']['bridge']['Service']['SaveProjectDialog']();
}

export function Startup(arg1) {
  return window['go']['bridge']['Service']['Startup'](arg1);
}

export function StrokePoint(arg1, arg2) {
  return window['go']['bridge']['Service']['StrokePoint'](arg1, arg2);
}

export function Undo() {
  return window['go']['bridge']['Service']['Undo']();
}

export function Version() {
  return window['go']['bridge']['Service']['Version']();
}
