// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyFilter(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['Service']['ApplyFilter'](arg1, arg2, arg3, arg4, arg5);
}

export function ApplyLevelsSample(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['Service']['ApplyLevelsSample'](arg1, arg2, arg3, arg4);
}

export function BeginFilterEdit(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['Service']['BeginFilterEdit'](arg1, arg2, arg3, arg4, arg5);
}

export function CameraRawAutoWhiteBalance() {
  return window['go']['bridge']['Service']['CameraRawAutoWhiteBalance']();
}

export function CameraRawDefringeSample(arg1, arg2, arg3) {
  return window['go']['bridge']['Service']['CameraRawDefringeSample'](arg1, arg2, arg3);
}

export function CameraRawScope() {
  return window['go']['bridge']['Service']['CameraRawScope']();
}

export function CameraRawWhiteBalanceSample(arg1, arg2) {
  return window['go']['bridge']['Service']['CameraRawWhiteBalanceSample'](arg1, arg2);
}

export function BeginStroke(arg1, arg2) {
  return window['go']['bridge']['Service']['BeginStroke'](arg1, arg2);
}

export function CancelFilterEdit() {
  return window['go']['bridge']['Service']['CancelFilterEdit']();
}

export function CommitFilter(arg1) {
  return window['go']['bridge']['Service']['CommitFilter'](arg1);
}

export function DocumentSnapshot() {
  return window['go']['bridge']['Service']['DocumentSnapshot']();
}

export function EndStroke() {
  return window['go']['bridge']['Service']['EndStroke']();
}

export function LayerHistogram() {
  return window['go']['bridge']['Service']['LayerHistogram']();
}

export function LayerOp(arg1, arg2) {
  return window['go']['bridge']['Service']['LayerOp'](arg1, arg2);
}

export function LevelsAuto(arg1) {
  return window['go']['bridge']['Service']['LevelsAuto'](arg1);
}

export function OpenProjectDialog() {
  return window['go']['bridge']['Service']['OpenProjectDialog']();
}

export function Redo() {
  return window['go']['bridge']['Service']['Redo']();
}

export function RenderHandler() {
  return window['go']['bridge']['Service']['RenderHandler']();
}

export function SampleLevelsPoint(arg1, arg2) {
  return window['go']['bridge']['Service']['SampleLevelsPoint'](arg1, arg2);
}

export function SaveProjectDialog() {
  return window['go']['bridge']['Service']['SaveProjectDialog']();
}

export function StrokePoint(arg1, arg2) {
  return window['go']['bridge']['Service']['StrokePoint'](arg1, arg2);
}

export function Undo() {
  return window['go']['bridge']['Service']['Undo']();
}

export function UpdateFilterPreview(arg1) {
  return window['go']['bridge']['Service']['UpdateFilterPreview'](arg1);
}

export function Version() {
  return window['go']['bridge']['Service']['Version']();
}
