// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginStroke(arg1:number,arg2:number):Promise<string>;
export function DocumentSnapshot():Promise<string>;
export function EndStroke():Promise<string>;
export function LayerOp(arg1:string,arg2:string):Promise<string>;
export function OpenProjectDialog():Promise<string>;
export function SaveProjectDialog():Promise<string>;
export function StrokePoint(arg1:number,arg2:number):Promise<string>;
export function Version():Promise<string>;
