// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function Load():Promise<bridge.WindowState>;

export function Save(arg1:number,arg2:number):Promise<void>;
