// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {render} from '../models';
import {domain} from '../models';

export function ActiveCanvasInfo():Promise<number>;

export function ActiveDocumentJSON():Promise<string>;

export function ActiveRev():Promise<number>;

export function ActiveSaveInfo():Promise<string>;

export function ActiveUsedPixels():Promise<number>;

export function BeginStroke(arg1:number,arg2:number):Promise<string>;

export function CloseTab(arg1:string):Promise<bridge.Snapshot>;

export function CommitImportedLayers(arg1:Array<bridge.pendingImportFile>):Promise<string>;

export function EditActive(arg1:string,arg2:any):Promise<string>;

export function EndStroke():Promise<string>;

export function FlattenActive():Promise<render.Bitmap>;

export function NewDocument(arg1:number,arg2:number,arg3:number):Promise<bridge.Snapshot>;

export function OpenDocument(arg1:string,arg2:domain.Document,arg3:Record<string, render.Bitmap>):Promise<bridge.Snapshot>;

export function RedoActive():Promise<string>;

export function RenderPNG(arg1:string):Promise<Array<number>>;

export function SaveActive(arg1:string):Promise<number>;

export function SelectTab(arg1:string):Promise<bridge.Snapshot>;

export function Snapshot():Promise<bridge.Snapshot>;

export function StrokePoint(arg1:number,arg2:number):Promise<string>;

export function UndoActive():Promise<string>;
