// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function CloseTab(arg1:string):Promise<bridge.Snapshot>;

export function NewDocument(arg1:number,arg2:number,arg3:number):Promise<bridge.Snapshot>;

export function SelectTab(arg1:string):Promise<bridge.Snapshot>;

export function Snapshot():Promise<bridge.Snapshot>;
