// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTab(arg1) {
  return window['go']['bridge']['Workspace']['CloseTab'](arg1);
}

export function NewDocument(arg1, arg2, arg3) {
  return window['go']['bridge']['Workspace']['NewDocument'](arg1, arg2, arg3);
}

export function SelectTab(arg1) {
  return window['go']['bridge']['Workspace']['SelectTab'](arg1);
}

export function Snapshot() {
  return window['go']['bridge']['Workspace']['Snapshot']();
}
