// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveCanvasInfo() {
  return window['go']['bridge']['Workspace']['ActiveCanvasInfo']();
}

export function ActiveDocumentJSON() {
  return window['go']['bridge']['Workspace']['ActiveDocumentJSON']();
}

export function ActiveRev() {
  return window['go']['bridge']['Workspace']['ActiveRev']();
}

export function ActiveSaveInfo() {
  return window['go']['bridge']['Workspace']['ActiveSaveInfo']();
}

export function ActiveUsedPixels() {
  return window['go']['bridge']['Workspace']['ActiveUsedPixels']();
}

export function BeginStroke(arg1, arg2) {
  return window['go']['bridge']['Workspace']['BeginStroke'](arg1, arg2);
}

export function CloseTab(arg1) {
  return window['go']['bridge']['Workspace']['CloseTab'](arg1);
}

export function CommitImportedLayers(arg1) {
  return window['go']['bridge']['Workspace']['CommitImportedLayers'](arg1);
}

export function EditActive(arg1, arg2) {
  return window['go']['bridge']['Workspace']['EditActive'](arg1, arg2);
}

export function EndStroke() {
  return window['go']['bridge']['Workspace']['EndStroke']();
}

export function FlattenActive() {
  return window['go']['bridge']['Workspace']['FlattenActive']();
}

export function NewDocument(arg1, arg2, arg3) {
  return window['go']['bridge']['Workspace']['NewDocument'](arg1, arg2, arg3);
}

export function OpenDocument(arg1, arg2, arg3) {
  return window['go']['bridge']['Workspace']['OpenDocument'](arg1, arg2, arg3);
}

export function RedoActive() {
  return window['go']['bridge']['Workspace']['RedoActive']();
}

export function RenderPNG(arg1) {
  return window['go']['bridge']['Workspace']['RenderPNG'](arg1);
}

export function SaveActive(arg1) {
  return window['go']['bridge']['Workspace']['SaveActive'](arg1);
}

export function SelectTab(arg1) {
  return window['go']['bridge']['Workspace']['SelectTab'](arg1);
}

export function Snapshot() {
  return window['go']['bridge']['Workspace']['Snapshot']();
}

export function StrokePoint(arg1, arg2) {
  return window['go']['bridge']['Workspace']['StrokePoint'](arg1, arg2);
}

export function UndoActive() {
  return window['go']['bridge']['Workspace']['UndoActive']();
}
